# Generated by Django 3.2.4 on 2021-10-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecogApi',
            fields=[
                ('no', models.AutoField(db_column='NO', primary_key=True, serialize=False)),
                ('image_1', models.CharField(db_column='IMAGE_1', max_length=100)),
                ('id', models.CharField(db_column='ID', max_length=45)),
                ('sex', models.IntegerField(db_column='SEX')),
                ('age', models.IntegerField(db_column='AGE')),
                ('company_name', models.CharField(db_column='COMPANY_NAME', max_length=100)),
            ],
            options={
                'db_table': 'FACE_RECOG_API',
                'managed': False,
            },
        ),
    ]
